services:
  app:
    build: .
    env_file: ./.env
    ports:
      - 8080:${SERVER_PORT}
    networks:
      - local
  kafka1:
    container_name: kafka1
    image: apache/kafka:4.1.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-c", "kafka-topics --bootstrap-server kafka1:9092 --list"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - 9092:9092
    networks:
      - local  
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    restart: always
    ports:
      - ${KAFKA_UI_PORT}:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092
      DYNAMIC_CONFIG_ENABLED: true
    networks:
      - local  
    depends_on:
      - kafka1

networks:
  local: